server:
  port : ${PORT:8080}

logging:
  level:
    ROOT: INFO
    '[com.billet.gestiontareas]': DEBUG

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://gestion-tareas.cfkyu1eqiipj.us-east-1.rds.amazonaws.com:5432/${DB_NAME:gestion-tarea}
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      poolName: Hikari
      auto-commit: false
      schema: public
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        '[id.new_generator_mappings]': true
        '[connection.provider_disables_autocommit]': true
        '[cache.use_second_level_cache]': false
        '[cache.use_query_cache]': false
        '[hibernate.generate_statistics]': false
        '[format_sql]': false


